project:
  type: website
  output-dir: docs

website:
  title: "Nishant Panicker"
  description: "Researcher, Musician, and Dancer"
  navbar:
    background: white # Keeps it minimalist
    foreground: dark
    left:
      - text: "Research"
        href: research.qmd
      - text: "Music"
        href: music.qmd
      - text: "Dance"
        href: dance.qmd
      - text: "Living" # Includes cooking and running
        href: hobbies.qmd
    right:
      - text: "CV"
        icon: file-pdf
        href: assets/cv.pdf
      - icon: instagram
        href: https://instagram.com/nishantpmusic
      - icon: github
        href: https://github.com/nishantp28

format:
  html:
    theme: 
      light: flatly # A very clean, academic-friendly theme
    css: styles.css
    toc: true # Adds a table of contents to your research/writing pages
